---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'avahi-daemon'
    - 'avahi-autoipd'
    - 'libnss-mdns'

- name: edit nsswitch.conf add mdns ipv6
  lineinfile:
    dest: '/etc/nsswitch.conf'
    state: present
    regexp: '^(.*)mdns4_minimal(.*)$'
    line: '\1mdns_minimal\2'
    backup: yes
    backrefs: yes

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
