---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'avahi-daemon'
    - 'avahi-autoipd'
    - 'libnss-mdns'

- name: edit nsswitch.conf add mdns ipv6
  replace:
    dest: '/etc/nsswitch.conf'
    regexp: 'mdns4_minimal'
    replace: 'mdns_minimal'
    backup: yes

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
